### ISSUE TITLE
player show 0/100 >> in server online 16/100

### ISSUE THREAD

**Issue by SugarPocket** [ServerSoftwareArchiveTeam/Tesseract#4]
#### OS and versions

* Tesseract:
* PHP: 7
* Server OS: ubuntu
* Game version: 1.1.4
* Server host: 
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
```

**Comment by shdudwns** [comment]
I don't now. @Asuna-Yuuki @Fabiansigala Do you know?

**Comment by BlawoHD** [comment]
Could be a bug of Mojang

**Comment by shdudwns** [comment]
@BlawoHD No!!! TESSERACT is bug;;

**Comment by shdudwns** [comment]
@Fabiansigala Do you know the error?

**Comment by G2PCraft** [comment]
No error in console

**Comment by shdudwns** [comment]
@Asuna-Yuuki

**Comment by shdudwns** [comment]
i can fix!

**Comment by shdudwns** [comment]
Fix
