### ISSUE TITLE
tesseract.jar

### ISSUE THREAD

**Issue by ExplodingCraftPE** [ServerSoftwareArchiveTeam/Tesseract#5]
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
``` need tesseract.jar
```

**Comment by shdudwns** [comment]
?

**Comment by shdudwns** [comment]
why?

**Comment by shdudwns** [comment]
It is java?

**Comment by ExplodingCraftPE** [comment]
or i need to install pmmp in my multicraft
